name: Style-Enforcer
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  format-check:
    name: Style Enforcement
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [min]
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install JuliaFormatter
        shell: julia --project=@format --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
      - name: Check formatting
        shell: julia --project=@format --color=yes {0}
        run: |
          using JuliaFormatter
          format(".", YASStyle(); verbose=true) || exit(1)
      # Add formatting suggestions to non-draft PRs even if "Check formatting" fails
      - uses: reviewdog/action-suggester@v1
        if: ${{ !cancelled() && github.event.pull_request.draft == false }}
        with:
          tool_name: JuliaFormatter
